title: UX consultant - Alexander af Ekenstam
email: alex@afekenst.am
baseurl: ""
url: "https://afekenst.am"
phone: +46702253880
phone_formatted: +46 70-225 38 80

# Meta
description: I collaborate with teams to create and improve the user experience of websites/apps by aligning the why, what and how with user needs.
keywords: user experience, user research, ux, rapid prototyping, wireframes, stockholm, remote work
image: https://afekenst.am/assets/images/meta/alexander-af-ekenstam.jpg
fb_app_id: 257953674358265
twitter: alexafekenstam
linkedin: alexanderafekenstam

collections:
  pages:
    output: true
    permalink: /:name

page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'cases'
    template: 'cases'
    name: 'case'
    dir: 'cases'

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: /assets/styles
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - bin