backend:
  name: git-gateway

display_url: https://afekenst.am
media_folder: "/assets/images"

collections: # A list of collections the CMS should be able to edit
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Page" # Used in the UI, ie.: "New Post"
    folder: "_pages"
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "SEO Description", name: "description", widget: "text"}